### ISSUE TITLE
stdin input

### ISSUE THREAD

**Issue by cbertelli** [webcarrot/csv2json#3]
thank you for providing such an efficient tool. Is there a way to overcome the
`-i file`
parameter and use the stdin (e.g. in a pipe?).
Using /dev/stdin generates a Memory error.

**Comment by webcarrot** [comment]
@cbertelli 
It was one of my first C program and at this moment I don't have knowledge to change it - I do not write anything in C-like languages for a very long time.

This program was written quite poorly and AFAIK it’s  read whole input file into memory (don’t  ask me why 🤦🏻 ) - so reading from stdin or file/stream/pipe/whatever that have no "real" length could be quite problematic.

Anyway - maybe I'll rewrite it in Rust as it’s memory safe and i want to learn this language.

Feel free to fork it and do whatever you want with it - i could change license from GNU to MIT if you want 😉 .

**Comment by cbertelli** [comment]
Thank you. I found my way with /dev/stdin that works, but the output is
anyway different from what I expected and still very similar to the CSV. I
ended by using a slightly more complex script with jq.
c

Il gio 17 set 2020, 11:15 Wojciech Wierchoła <notifications@github.com> ha
scritto:
